@startuml カレーライスの作り方
title カレーライスのつくりかた

start
:材料を買う;
:お米を研ぐ;

fork
    :野菜、肉等を切る;
    :野菜、肉等をあらかじめ炒める;
    :野菜、肉などを固い順に鍋に入れて煮込む;
    :カレールーを入れて混ぜる;
    

fork again

    :ご飯を炊く;

end fork

:皿にご飯とルーをよそう;
:完成;

stop
@enduml