@startuml ライントレーサー
class ライントレーサー
class 光トレーサー
class 右モーター
class 左モーター
class CPU
class 電源sw

ライントレーサー "1"*--"1" 光トレーサー
ライントレーサー "1"*--"1" 右モーター
ライントレーサー "1"*--"1" 左モーター
ライントレーサー "1"*--"1"  CPU
ライントレーサー "1"*--"1"  電源sw
@enduml