@startuml 演習4-1
hide footbox
autonumber

skiparam style strictuml
actor "<u>:客</u>" as custmer
participant":<u>:フロア店員</u>" as clerk
participant":<u>:フロア店員</u>" as cook
activate custmer
    custmer -> clerk:ラーメンを注文する
    activate clerk
        clerk -> cook:調理を支持する
        activate cook
           cook -> cook: 調理する 
           clerk <- cook: ラーメン
        deactivate cook
        custmer <-- clerk ラーメン
        

    
clerk
@enduml