@startuml 商品情報登録
actor 会員
会員 -> 商品検索画面 : 商品検索をリクエスト
商品検索画面 -> 商品検索システム : 商品検索リクエスト
商品検索システム -> 商品DB : 商品情報検索リクエスト
商品DB -> 商品検索システム : 商品情報検索結果
商品検索システム -> 商品検索画面 : 商品情報を返却
商品検索画面 -> 会員 : 商品情報を表示
@enduml