@startuml  Web画像検索
actor ユーザー
ユーザー -> ブラウザ : 画像リンクのクリック
ブラウザ -> Webサーバー : 画像のファイル名リクエスト
Webサーバー -> 画像サーバー : 画像のファイル名リクエスト
画像サーバー -> Webサーバー : 画像ファイル送信
Webサーバー -> ブラウザ : 画像ファイル送信
ブラウザ -> ユーザー : 画像表示
@enduml